### PR TITLE
Added support for removing DNS A records. Fixes #6 and fixes #7

### LINKED ISSUE #6: xDnsARecord Test-TargetResource returns incorrect result
The first configuration completes as the resource doesn't exist. A second pass, however, fails as the resource attempts to recreate the A record (presumably as the Test-TargetResource function returns $false when it shouldn't?).
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSC
LocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer DC1 with user sid S-1-5-21-369477980-2918075026-776283088-500.
VERBOSE: [DC1]: LCM:  [ Start  Set      ]
VERBOSE: [DC1]: LCM:  [ Start  Resource ]  [[xDnsARecord]test_virutalengine_co_uk]
VERBOSE: [DC1]: LCM:  [ Start  Test     ]  [[xDnsARecord]test_virutalengine_co_uk]
VERBOSE: [DC1]:                            [[xDnsARecord]test_virutalengine_co_uk] Testing for DNS test in virtualengine.co.uk
VERBOSE: [DC1]:                            [[xDnsARecord]test_virutalengine_co_uk] Looking up DNS record for test in virtualengine.co.
uk
VERBOSE: [DC1]: LCM:  [ End    Test     ]  [[xDnsARecord]test_virutalengine_co_uk]  in 0.0160 seconds.
VERBOSE: [DC1]: LCM:  [ Start  Set      ]  [[xDnsARecord]test_virutalengine_co_uk]
VERBOSE: [DC1]:                            [[xDnsARecord]test_virutalengine_co_uk] Creating for DNS 1.2.3.4 in virtualengine.co.uk
Failed to create resource record test in zone virtualengine.co.uk on server localhost.
    + CategoryInfo          : ResourceExists: (test:) [], CimException
    + FullyQualifiedErrorId : WIN32 9711,Add-DnsServerResourceRecordA
    + PSComputerName        : localhost
 
VERBOSE: [DC1]: LCM:  [ End    Set      ]  [[xDnsARecord]test_virutalengine_co_uk]  in 0.0150 seconds.
The PowerShell DSC resource MSFT_xDnsARecord threw one or more non-terminating errors while running the Set-TargetResource 
functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more 
details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
```

### LINKED ISSUE #7: Cannot remove A records with xDnsARecord
There is no Ensure property on the xDnsARecord resource meaning that we cannot remove old/stale records if required :S

### PR DESCRIPTION
**Pull request by iainbrighton**
- Fixes #6
 - Reads IPv4 address from $record.RecordData.IPv4Address.IPAddressToString property
- Fixes #7:
 - Added 'Ensure' parameter to xDnsARecord
 - Updated Pester test coverage
 - Updated readme.md

### CODE REVIEW

**Comment by iainbrighton** [comment]
Any update on this pull request? Been waiting for a review for coming up 2 months?!

**Comment by iainbrighton** [comment]
@KarolKaczmarek can you get someone to review this pull request? I can't send another pull request for the xDnsServerPrimaryZone (issue #5) until this is merged (as my dev branch has these fixes in it!) :|

**Comment by KarolKaczmarek** [comment]
Will do! Sorry for the wait :(

**Comment by HemantMahawar** [comment]
LGTM

**Pull request merged**
