### PR TITLE
Fix name param to ZoneName in Get-TargetResource - Fixes #63

### LINKED ISSUE #63: Get-TargetResource always returns null for Zone Name
it is referencing $dnsServerZone.Name instead of $dnsServerZone.ZoneName

### PR DESCRIPTION
**Pull request by gerane**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/64)

### CODE REVIEW

**Comment by johlju** [comment]
Thank you for sending in this PR! Looking good! Just one thing, could you please add an entry to the Unreleased section of the README.md?

Also, maybe you need to change the PR title to `Fix name param to ZoneName in Get-TargetResource - Fixes #63`. It will then auto close the issue when merged, not sure if the current PR title will do that :thinking: 

The unit test did not catch this, and looking at the unit test it really needs an overhaul, so I suggest merging this without a need for adding this change to the unit test. But if you'd like trying out Pester and adding a tests for this change to the unit test, then you are more than welcome, but don't feel that you have to. 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdnsserver/64#-:-L5KTZubBYrvt-P1tcnk:blrlyd5)*

**Comment by gerane** [comment]
I won't have time atm to look into the unit tests. I can try to look into it when I can make some free time.

**Comment by johlju** [comment]
:lgtm:

@kwirkykat The unit test did not catch this, and looking at the unit test it really needs an overhaul, so I suggest merging this simple PR without a need for adding this change to the unit test. If you like this to be added to the unit test @gerane says he can do that when he get free time.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdnsserver/64#-:-L5SgLprUfduRj-0NfDE:b-hadh8n)*

**Comment by johlju** [comment]
@gerane Sorry it took so long to merge this simple fix.

**Pull request merged**
