### PR TITLE
Adding Ptr record support to xDnsRecord

### PR DESCRIPTION
**Pull request by regedit32**
Adding PTR record support to xDnsRecord. #34

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/60)

### CODE REVIEW

**Comment by TraGicCode** [comment]
Hey @regedit32,

This looks good to me.  Are you able to add some unit tests to cover this?

**Comment by johlju** [comment]
Labeling as abandoned since it has gone 14 days until last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by angystardust** [comment]
@regedit32 are you still interested in pushing ahead your PR?

**Comment by regedit32** [comment]
Sure thing, I'll add unit test this week.

**Comment by regedit32** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/powershell/xdnsserver/60#-LBttRCa9W5vluH-rCkG:-LEIAxIZB2AiUS0Zm0nT:b-896fix) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add unit test to test this change (as per @tragiccode comment).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/60)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[Tests/Unit/MSFT_xDnsRecord.Tests.ps1, line 94 at r4](https://reviewable.io/reviews/powershell/xdnsserver/60#-LEJVGEoD2PZw8ggrCMp:-LEJVGEoD2PZw8ggrCMq:bxxme1n) ([raw file](https://github.com/powershell/xdnsserver/blob/bb645fb1db1eb6243e483cc3b36926abb9bd691d/Tests/Unit/MSFT_xDnsRecord.Tests.ps1#L94)):*
> ```PowerShell
>         #region Function Test-TargetResource
>         Describe "MSFT_xDnsRecord\Test-TargetResource" {
>             foreach ($dnsRecord in $dnsRecordsToTest)
> ```

Non-blocking: Maybe we could have used `-TestCases` for this instead. **But good as-is.**
https://github.com/pester/Pester/wiki/It#testcases
http://mikefrobbins.com/2016/12/09/loop-through-a-collection-of-items-with-the-pester-testcases-parameter-instead-of-using-a-foreach-loop/

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/60#-:-LEJV6Cf9PLhxdjdh2TS:bnfp4nl)*

**Pull request merged**
