### PR TITLE
xDnsServerSetting: Add read-only property DsAvailable

### PR DESCRIPTION
**Pull request by claudiospizzi**
Fix for issue https://github.com/PowerShell/xDnsServer/issues/66

The DsAvailable property is a read-only output property on the xDnsServerSetting resource.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/69)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks for resolving this issue! Just a two review comments.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/powershell/xdnsserver/69#-LB5yNv76Ddujebrjo73:-LB5yNv76Ddujebrjo74:bkqilrl) (no related file):*
Please add an entry about this change under the change log Unreleased section in the README.md 

---

*[DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof, line 50 at r1](https://reviewable.io/reviews/powershell/xdnsserver/69#-LB5xmqmEfdxEEuLqCdh:-LB5xmqmEfdxEEuLqCdi:bfdy4f0) ([raw file](https://github.com/powershell/xdnsserver/blob/2e5b24e135ffc0c058bf79b0d49a9214e08dc867/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof#L50)):*
> ```
>     [Write, Description("Specifies whether the DNS Server writes NS and SOA records to the authority section on successful response.")] Boolean WriteAuthorityNS;
>     [Write, Description("Time, in seconds, the DNS Server waits for a successful TCP connection to a remote server when attempting a zone transfer.")] Uint32 XfrConnectTimeout;
>     [Read, Description("Indicates whether there is an available DS on the DNS Server.")] Boolean DsAvailable;
> ```

This property seems not to be tested for the `Get-TargetResource` function in the unit test. Could you please make sure this property is tested in the unit test.

---

*[DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof, line 50 at r1](https://reviewable.io/reviews/powershell/xdnsserver/69#-LB5xvgq1KDeH60sknhK:-LB5xvgq1KDeH60sknhL:b-y5poml) ([raw file](https://github.com/powershell/xdnsserver/blob/2e5b24e135ffc0c058bf79b0d49a9214e08dc867/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof#L50)):*
> ```
>     [Write, Description("Specifies whether the DNS Server writes NS and SOA records to the authority section on successful response.")] Boolean WriteAuthorityNS;
>     [Write, Description("Time, in seconds, the DNS Server waits for a successful TCP connection to a remote server when attempting a zone transfer.")] Uint32 XfrConnectTimeout;
>     [Read, Description("Indicates whether there is an available DS on the DNS Server.")] Boolean DsAvailable;
> ```

Please add this property to the resource parameters in README.md.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/69#-:-LB5xcVW64eCrV2Bi6V4:b-orl071)*

**Comment by johlju** [comment]
Became total of four comments :slightly_smiling_face: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof, line 50 at r1](https://reviewable.io/reviews/powershell/xdnsserver/69#-LB5zXxZ1i3rL82ajQIa:-LB5zXxZ1i3rL82ajQIb:b5ffakj) ([raw file](https://github.com/powershell/xdnsserver/blob/2e5b24e135ffc0c058bf79b0d49a9214e08dc867/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof#L50)):*
> ```
>     [Write, Description("Specifies whether the DNS Server writes NS and SOA records to the authority section on successful response.")] Boolean WriteAuthorityNS;
>     [Write, Description("Time, in seconds, the DNS Server waits for a successful TCP connection to a remote server when attempting a zone transfer.")] Uint32 XfrConnectTimeout;
>     [Read, Description("Indicates whether there is an available DS on the DNS Server.")] Boolean DsAvailable;
> ```

Could you look and see if you can test this property in the integration tests as well?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/69#-:-LB5zQeSEJ47nAbTAxsm:b-z3dqb5)*

**Comment by claudiospizzi** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/xdnsserver/69#-LB5yNv76Ddujebrjo73:-LB6_QZg6AmFUh-DLu4N:bb7f2mf) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add an entry about this change under the change log Unreleased section in the README.md 
</blockquote></details>

done

---

*[DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof, line 50 at r1](https://reviewable.io/reviews/powershell/xdnsserver/69#-LB5xmqmEfdxEEuLqCdh:-LB6_Uyn-7tLuffpNG2M:bwgunul) ([raw file](https://github.com/powershell/xdnsserver/blob/2e5b24e135ffc0c058bf79b0d49a9214e08dc867/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof#L50)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This property seems not to be tested for the `Get-TargetResource` function in the unit test. Could you please make sure this property is tested in the unit test.
</blockquote></details>

Added. Because it's a read only property, it's a simple test just checking if the mocked value is passed through.

---

*[DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof, line 50 at r1](https://reviewable.io/reviews/powershell/xdnsserver/69#-LB5xvgq1KDeH60sknhK:-LB6_beK7EA4COQczb9C:bb6un1j) ([raw file](https://github.com/powershell/xdnsserver/blob/2e5b24e135ffc0c058bf79b0d49a9214e08dc867/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof#L50)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add this property to the resource parameters in README.md.
</blockquote></details>

Done

---

*[DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof, line 50 at r1](https://reviewable.io/reviews/powershell/xdnsserver/69#-LB5zXxZ1i3rL82ajQIa:-LB6_v6U2cHy7dGjsRUY:bhrqfhq) ([raw file](https://github.com/powershell/xdnsserver/blob/2e5b24e135ffc0c058bf79b0d49a9214e08dc867/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof#L50)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you look and see if you can test this property in the integration tests as well?
</blockquote></details>

I think this is not required, because it's  a read-only property.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/69)*

**Comment by claudiospizzi** [comment]
Should now be ready

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/69#-:-LB6a14C-zBZfcEF1Tu8:bd5udnc)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/69#-:-LB6b3JGA4z_B3RcfW6g:bnfp4nl)*

**Comment by johlju** [comment]
@claudiospizzi Great work on this! Thanks! 😄

**Pull request merged**
