### PR TITLE
Added ability to create reverse lookup zone.

### PR DESCRIPTION
**Pull request by corydwood**

### CODE REVIEW

**Comment by iainbrighton** [comment]
@corydwood Thanks for your contribution! However, I'm not entirely sure you needed to add all these additions.. It's always been possible to create reverse lookup zones with this resource, but that has obviously not been well documented.

There are really two changes here:
 1. Creating reverse lookup zones
 2. Adding AD integrated zone support

The AD integrated zones were earmarked for a separate resource due to all the other parameters available that would clutter this resource unnecessarily - see #5. I'm positive we can integrate your AD zone changes in some fashion. Now, whether these all get bundled into one resource is up for discussion! @TravisEz13 @PlagueHO thoughts?

**Comment by corydwood** [comment]
I didn't realize you could create a reverse zone with the -Name parameter instead of -NetworkID, but I just tried it and it works, so I agree that most of these changes aren't needed if you want to keep AD integrated zone creation in a separate resources.

The fixes that still need to be made are the ordering of the values after the **-f** in the verbose messages and replacing the invalid **$dnsServerZone.Name** with **$dnsServerZone.ZoneName**.

**Comment by TravisEz13** [comment]
@corydwood @iainbrighton Can one of you file an issue to document how to create a reverse lookup zone with the existing resource if it's not well documented currently with a small sample of how to do it?

**Comment by corydwood** [comment]
@TravisEz13 @iainbrighton I just did: #18.

**Comment by TravisEz13** [comment]
@corydwood Do we need to leave this PR open?  I thank based on the comments it would be best to open a new one just fixing the issues you mentioned

**Comment by iainbrighton** [comment]
@corydwood we still need an AD-integrated zone resource so all is not lost! Fancy taking a shot at that? If so, log an issue with proposed implementation and we'll go from there..

A friendly bit of advise: in future, log an issue first - before starting any work! I've found this out to my cost in the past as well :(

**Pull request closed without merging**
