### PR TITLE
ResourceName: xDnsServerClientSubnets

### PR DESCRIPTION
**Pull request by 1800Zeta**
#### Pull Request (PR) description
Adds configuration of DNS Server Client Subnets for use with DNS policies

#### This Pull Request (PR) fixes the following issues
- Part of #95 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/96)

### CODE REVIEW

**Comment by 1800Zeta** [comment]
AppVeyor is failing due to missing cmdlets. They are part of RSAT for Windows Server 2016 and above. The cmdlets are available on Windows 10 RSAT as well.

**Comment by johlju** [comment]
@1800Zeta We could change the build worker to use Windows Server 2016 by changing the image as below in the appveyor.yml

https://github.com/PowerShell/SqlServerDsc/blob/7209a03e43f7512dea90c562095bbf99789a43dd/appveyor.yml#L12

Build worker images:
https://www.appveyor.com/docs/windows-images-software/

/cc @indented-automation do you see an issue changing this? It would be possible to build a job matrix that runs different images so all test runs on both 2012R2 and 2016, but this test only runs on 2016. See SqlServerDsc for examples.

**Comment by johlju** [comment]
@1800Zeta See other tests that are failing. It is not allowed/possible to have an array as Key. The resource instance would never be unique.

https://ci.appveyor.com/project/PowerShell/xdnsserver/builds/25279752#L419

**Comment by 1800Zeta** [comment]
Thank you @johlju  will take a look at those

**Comment by 1800Zeta** [comment]
Hi @johlju I have now fixed the issues in the build and all pass. Is there anything else I need to do?

Thanks

**Comment by 1800Zeta** [comment]
Thanks @indented-automation I have made the majority of changes, just working on the test script now.

**Comment by 1800Zeta** [comment]
Thank you @indented-automation . I will take a look at doing it this way. It's my first time doing pester so learning as I go.

**Comment by 1800Zeta** [comment]
Hi @indented-automation 

I've been working on the tests and have come across an issue with the splatting. I couldn't get a test to fail when values didn't match.

https://beatcracker.wordpress.com/2014/12/01/splatting-and-mandatory-parameters/

This is the issue. I can resolve by not using splatting or doing everything as Custom Objects and piping them through. Any suggestions on which is best way to do things? I think using the custom object and piping is the best way as it's easier to 'skip' non mandatory params.

Thanks

**Comment by 1800Zeta** [comment]
Morning @indented-automation I was seeing it on Get-TargetResource, then Test and then Set. PowerShell 6.2 and 5.1.  If I changed the commands to Get-TargetResource -param value -param value it worked fine. When using Get-TargetResource @params or Get-TargetResource $Params it was just not returning the correct test results. It looked like it was passing but when setting it so it should fail it wasn't

**Comment by 1800Zeta** [comment]
I went through and I am not actually passing more parameters than it will accept. Switching to using value from pipeline did resolve the issue.

**Comment by johlju** [comment]
@1800Zeta Awesome work on this one! Let me or @indented-automation know if you need any assistance with these comments. 🙂

**Comment by johlju** [comment]
@indented-automation looks good to me, up to you if you want to merge and add integration test later, should add an issue for that in that case so it can be tracked.

**Pull request merged**
